// NOTE: this will be generated by nrg using a template
import remoteServer from "./remote-server/client";
import yourNode from "./your-node/client";

remoteServer("remote-server");
yourNode("your-node");
