// NOTE: this file is provided by the user
// NOTE; this file is generated by nrg
import { registerType } from "../../../core/client";
import form from "./Form.vue";
import schema from "../schemas/config";

export default registerType({
  category: "config",
  color: "#a6bbcf",
  form: form,
  schema: schema,
});
