// NOTE: this file is provided by the user
// NOTE; this file is generated by nrg
import { registerType } from "../../../core/client";
import component from "./Form.vue";

export default registerType({
  category: "function",
  color: "#FFFFFF",
  inputs: 1,
  outputs: 1,
  icon: "vue.png",
  form: {
    component,
    disableSaveButtonOnError: true,
  },
  onPaletteAdd: () => {
    console.log("NODE TYPE REGISTERED ON THE PALETTE");
  },
});
