// NOTE: this file is provided by the user
// NOTE; this file is generated by nrg
import { registerType } from "../../../core/client";
import form from "./Form.vue";
import schema from "../schemas/config";

export default registerType({
  category: "function",
  color: "#FFFFFF",
  inputs: 1,
  outputs: 1,
  icon: "vue.png",
  form,
  schema,
  onPaletteAdd: () => {
    console.log("NODE TYPE REGISTERED ON THE PALETTE");
  },
});
