// NOTE: this will be generated by nrg using a template
import remoteServer from "./nodes/remote-server/client";
import yourNode from "./nodes/your-node/client";

// TODO: is there a use case for controlling the order nodes in the editor are registered?
async function registerNodes() {
  try {
    await Promise.all([remoteServer("remote-server"), yourNode("your-node")]);
    console.log("All node types registered in parallel");
  } catch (error) {
    console.error("Error registering node types:", error);
  }
}

registerNodes();
