// NOTE: this module is optional and it is generated by nrg when client.build.entryPoint isn't provided. Use this if you need to control the order nodes are registered in the editor.
import remoteServer from "./nodes/remote-server/client";
import yourNode from "./nodes/your-node/client";

// TODO: is there a use case for controlling the order nodes in the editor are registered?
export default async function () {
  try {
    await Promise.all([remoteServer("remote-server"), yourNode("your-node")]);
    console.log("All node types registered in parallel");
  } catch (error) {
    console.error("Error registering node types:", error);
  }
}
