// NOTE: this module is optional and it is generated by nrg when server.build.entryPoint isn't provided. Use this if you need to control the order nodes are registered in the server.
import YourNode from "./nodes/your-node/server";
import RemoteServerConfigNode from "./nodes/remote-server/server";
import { registerType } from "./core/server";

// NOTE: this root module can be used to manually control the order nodes are registered
// TODO: define RED type
export default async function (RED: any) {
  try {
    // TODO: the order nodes are registered will be defined in nrg.config.ts. If not provided, it will be registered alphabetically based on the folder names
    // TODO: investigate if it is possible to run Khan's algorithm to determine the registration order
    await registerType(RED, "remote-server", RemoteServerConfigNode);
    await registerType(RED, "your-node", YourNode);

    // TODO: add the order in the message
    console.log("All node types registered in series");
  } catch (error) {
    console.error("Error registering node types:", error);
  }
}
