// NOTE: this module is generated by nrg
import init from "./index.server";

// TODO: define RED type
export default async function (RED: any) {
  try {
    console.log("Running provided init");
    await init(RED);
    console.log("Finished running provided init");
  } catch (error) {
    console.error("Error while running provided init:", error);
  }
}
