// NOTE: if provided, it overwrites what is generated by vite
// NOTE: use this to control the registration
import { registerTypes } from "@bonsae/nrg/client";
import remoteServer from "./nodes/remote-server";
import yourNode from "./nodes/your-node";

registerTypes([remoteServer, yourNode]);
