// NOTE: this file is provided by the user
// NOTE; this file is generated by nrg
import { defineNode } from "../../../core/client";
import component from "../components/remote-server-form.vue";

export default defineNode({
  category: "config",
  color: "#a6bbcf",
  form: {
    component,
    disableSaveButtonOnError: true,
  },
});
