// NOTE: if provided, it overwrites what was generated by vite
import { defineNode } from "@bonsae/nrg/client";
import component from "../components/remote-server.vue";

export default defineNode({
  type: "remote-server",
  category: "config",
  color: "#a6bbcf",
  form: {
    component,
  },
});
