// NOTE: if provided, it overwrites what was generated by vite
import { defineNode } from "@bonsae/nrg/client";
import component from "../components/your-node.vue";

export default defineNode({
  type: "your-node",
  category: "function",
  color: "#FFFFFF",
  inputs: 1,
  outputs: 3,
  form: {
    component,
  },
  onPaletteAdd: () => {
    console.log("NODE TYPE REGISTERED ON THE PALETTE");
  },
  onEditResize: () => {
    console.log("resizing editor form");
  },
});
